### ISSUE TITLE
[IDEA] Build and list integrations to prominent services

### ISSUE THREAD

**Issue by rcarey** [joomla/joomla-marketing#134]
As I review various SaaS services and look at their integration list, I occaisionally see WordPress listed as an integration option.  I wish I could see the Joomla logo along with other prominent services such as Trello, MailChimp, Google Docs, GitHub, etc.  As I review the lists on various sites, the logos stick in my mind and reinforce their brand.  (An example list where WP got in:  https://www.teamwork.com/desk-integrations) 

If integrations to Joomla was listed in more of these lists, that would increase its visibility and the credibility - probably leading to more people considering Joomla.  I assume the largest hurdle is to discover useful integrations and build them.  After that, it seems like Zapier and others would be happy to list them.  The problem, as I suppose it, is that there is little-to-no business value for someone to actively develop potential integrations.  

But I do think it has value as a 'marketing' initiative for Joomla.  I realize there is a policy of not paying developers, but if this is seen as a marketing initiative, perhaps there can be an initiative to partially fund or commission some developer or company to develop and distribute valuable integrations as a way to get Joomla listed as a viable option on the many lists out there.   If Joomla does not invest in this, then who else will?

**Comment by mbabker** [comment]
How many of these integrations are built by the third party whom is linked to (in this case, how many are developed by Automattic/WordPress) versus how many are built by the base service (in this case, how many were developed by Teamwork)?

We already have a hard enough time getting contributors to our core code.  I don't think it's a good priority to write integrations to third party platforms that are going to become abandonware because the project doesn't have the resources to maintain them once written (and we already have enough abandonware resources in our product line).

**Comment by rcarey** [comment]
I don't know the answer regarding who are the ones developing these,  It would be insightful to know.  Maybe there is value to developers of certain extensions.
I understand the challenge of volunteers, and I probably agree that this is not a high priority for a scarce resource.  But if marketing is going to invest money in some initiatives, getting listed as a viable resource seems to be an initiative worth considering.  (I admit to a counter-opinion: I believe J can do more and be more if we did not rely 100% on unpaid volunteers.)

**Comment by brianteeman** [comment]
https://connect.mailchimp.com/search?q=joomla

**Comment by Sandra97** [comment]
Marketing has a very low budget and we lack of volunteers everywhere. I'm closing this issue. Can still be re-opened.
