### ISSUE TITLE
[sponsors] Joomla Website Installation Statistics

### ISSUE THREAD

**Issue by JoeJoomla** [joomla/joomla-marketing#15]
We need a way to tell our partners, sponsors & others some basic statistics about website installation demographics.

It can be simple such as how many installations are individual domains and how many are business domains.

Potential sponsors would like to not only know how many Joomla installations in general there are but also what size/level they are such as small, medium size businesses, enterprise level.

**Comment by mbabker** [comment]
From a marketing perspective I agree with this, but it would have to be solely marketing/research based work and not tied into core's stats collection system.  I had a similar type of discussion at the office this week and we pretty much agreed it's best for the core project's integrated stats system to  remain mostly anonymous and opt-in (with Apache logs and the database records one could in theory trace stuff back to specific hosts/servers/domains but we aren't doing that).

Note I'm 99% sure what you had in mind wasn't concerned with tying into that, but I'm just throwing it out there because I've seen some mention about core being able to collect that data in the past.

**Comment by JoeJoomla** [comment]
Hi Michael,

I totally agree with you that this shouldn't be part of the anonymous statistics plugin.

We are thinking that somehow we would get stats like this from web hosting companies or some other method. We are looking for ideas on how to approach this.

Joe

**Comment by cpfeifer** [comment]
This is the CiviCRM dashboard, it is an anonymized data plugin that's part of their platform. It shows a lot of very useful information: https://stats.civicrm.org/?tab=sites

The guy who made this lives right down the street from me and explained the concept, every piece of data is anonymous and can never be combined to create a profile. I don't really have any preference on how it's done, this is just the best example I've seen of something like this. 

I personally think something like this would help us in many ways, it could be used for marketing and many other things. I think there is a lot of value to having this data.

**Comment by mbabker** [comment]
CiviCRM's got a nice dashboard, and they've got a lot of nice data.  I don't think though that the same could be done in Joomla.  When you start pulling data like the number of users registered on a site or the extensions installed you're starting to get into avenues to identify sites and we're trying to avoid that.  Plus, IMO any additional data collection should be as open as the tech data we grab, so freely readable via API and minimal data filtering (we group PHP and database versions by "minor" branch unless you pass an authentication header to get raw data, otherwise everything is freely readable) and you can't really make that promise with openness when you have extension metrics.

I don't want to sound like I'm discouraging anyone, but I do think when you start getting into particular details of a site you have to be careful.  It's already been a tough enough fight for the tech data and none of that is really identifying beyond sharing details of the tech stack powering a server.

**Comment by cpfeifer** [comment]
I totally hear you Michael, and it's not discouraging. I know this exact thing won't work for us and I'm not suggesting we do exactly this, it's just an example. Personally, I'd rather beat my head against a wall than touch the community anonymous data collection debate with a ten foot pole. There are valid points on both sides, but that's not the issue here. 

The real issue is that we have no accurate usage data to work with and I believe that hurts us. I'm open to anything that helps us get more information. Anything we can do is better than nothing, that's how I'm looking at it, but any solution has to work for us and the community. 

I think a good place to start is finding out what options we do have and what we can do with them. I'm open to anything that helps.

**Comment by mbabker** [comment]
Personally, I think it's safe to assume based on numbers that a majority of Joomla! 3.5+ sites have opted in to sending tech data to the server.  That's got just over 568K records in it and there are numbers that roughly 2.8 million sites are Joomla.  So that gives a very high level of numbers to work with and possibly some ideas on what types of research to look into, but it's not really the type of detail that folks are interested in.

I don't think it'd be an issue to develop a second plugin similar to the tech stats and allow people who are willing to share data to install that.  We'd probably need to run a second stats server for its data and make changes to that based on lessons learned deploying the original stuff plus changes to the data model for storage.  The one thing that concerns me though about grabbing that data is grabbing the list of extensions (I think the furthest we could go without getting into the identifying info stuff would be a count of extensions separated by status (enabled, protected, disabled, etc.)).  Still overall it's technically feasible to do but without it being a part of the core distro its data would be heavily skewed.  The one thing I'd be adamant about though is that the data be as transparent as what we're doing now, and again that'd complicate matters because maybe some folks are willing to share these types of details but don't want it to be part of an aggregate count.

**Comment by cpfeifer** [comment]
I'm with you on the data collection being transparent, privacy is of the utmost importance and should never be any intention of collecting anything that could be used to harm people.

I think an optional non-core plugin is a good idea, and it's something the UX team has discussed, along with expanding what anonymous data is collected. Even something where people could send in their data that is accessible from the dashboard or works with the new system information feature. If we put in front of people as an option they will usually respond to it.

Based on what you're saying, and the UX research for the J3.5 release (which I'll be publishing shortly), I think the general consensus is that people are okay with us gathering usage data as long as it isn't personal data and is only used to improve Joomla. I know there are a lot of privacy and technical considerations, but if we can deal with those effectively I think we can find a solution. Like I said, anything is better than nothing and I'm open to anything :)

**Comment by JoeJoomla** [comment]
I was wondering what incentive there is for a Joomla website owner to be willing to share any kind of statistical information.

Other than it being very cool to see the kinds of stats that CiviCRM have on display publicly is there any benefit to the end user of the website? 

Maybe its enough to just have stats available for the general public.

**Comment by cpfeifer** [comment]
I think the only incentive we have is that it helps make Joomla better. I think most people are willing to help if all they need to do is spend one second pushing a button. The key is putting the option in front of them and making it so easy that it's a no brainer, and then showing them later how it actually helped us. 

We're not really asking people for much effort or commitment here, we're only asking them to say it's okay. Right now, the only incentive I see for providing anonymous data is to get the persistent message to go away. This is not a method I like very much, but you can only ignore it for so long and annoying as it is, it seems to be working. 

Just for the record, I'm not in favor of adding any more persistent messages, I think we can find a better way to communicate with our users :)

**Comment by mikeveeckmans** [comment]
Hi All,
I do agree it would be great to have such stats... Allthough i do understand the difficulties that come with it... 

@JoeJoomla , as @cpfeifer said, there's only 1 incentive active at the moment, we could set up another one... just have to brainstorm on that then... 

@mbabker i agree with your POV on what we can collect from the extensions. I think if we collect just the number of extensions installed ( active, disbaled) that might help us already. (protected are in my opinion not necessary as they are core extensions). Where can the MWG help in a possible development of the stats collecting plugin?

**Comment by ufuk-avcu** [comment]
I close this also, because of no respone since one year. If someone is willing to start with this project can contact me.
