### ISSUE TITLE
Joomla 4 - Newsletter Template Integrator

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#163]
The Marketing team is looking for a volunteer with AcyMailing knowledge to transform 3 PSD templates into 3 AcyMailing Templates.

**Comment by acvmultimedia** [comment]
Hi @Sandra97 for which version of ACYmailing? The new version is "drag and drop" constructor. Can I see those PSD?

**Comment by Sandra97** [comment]
We're using 5.10.x version. I'll grant you an access to the PSD files. Thanks Josean!

**Comment by acvmultimedia** [comment]
I've seen the newsletter designs and yes, I generally like them. The problem I see is that we will never get those designs to be perfect in all the different Outlook's on the market. I know this because we have made many templates in the past with ACYba and because even with Mailchimp the same thing happens when the newsletter gets complicated. My advice is if you can use ACYmailing 6.x and adapt it to your drag and drop. The display result is always better.

1. Do we have that possibility, to change to 6.x?
2. A backend joomla user would be fine just for acymainling.

**Comment by Sandra97** [comment]
I like them too but for sure they need to be adapted. I've never tried ACY 6. I have plenty of existing newsletter templates. Do you know if they will still work if we switch to 6 or they will need to be rewritten?

**Comment by acvmultimedia** [comment]
They work perfectly, ACY 6 gives the option to continue editing as always the old ones and the option of drag & drop for others, they coexist well.

Besides, the incredible thing is that ACY 5 and ACY 6 would be at the same time and this for the calmness of all at the beginning is great, then if with time we like it and it works well we remove ACY5.

**Comment by Sandra97** [comment]
That's a good news.

@Joomv is the webmaster of the property hosting ACYmailing (community.joomla.org). Rowan, would it be possible for you to install ACY 6 and provide an access to Josean? Thanks

**Comment by acvmultimedia** [comment]
Perfect @Sandra97 , thanks

**Comment by acvmultimedia** [comment]
Hello @Sandra97 I already have access and consent to install ACYmailing 6 in the sidekick version. Rowan gave me access a few days ago.

**Comment by Sandra97** [comment]
Great! Thanks Josean

**Comment by andreagentil** [comment]
@marcodings @wilsonge @agerix @mqueme
The template for the J4 newsletter is almost ready. Who will be in charge of sending it?

**Comment by andreagentil** [comment]
https://volunteers.joomla.org/teams/marketing/reports/1264-joomla-4-marketing-team
