### ISSUE TITLE
Article on Cloudflare 

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-marketing#47]
https://docs.google.com/a/community.joomla.org/document/d/1Lzbv7d56z7x1s26Hf2je012S4s5LBWamFOgYDK6qCx0/edit?usp=sharing 

Release an article over the weekend about the cloudflare issue telling Joomla users what we can do. I'm using this as a base article and twisting it into my own words and adding in the Joomla specific information https://www.wordfence.com/blog/2017/02/cloudflare-data-leak/

**Comment by cpaschen** [comment]
George,

Just need to clarify some 'details'. (I use cloudflare for one client site so I've been following this and got notifications from Cloudflare).

1. "data to other users"
Are we sure that it potentially leaked data to other users. I just re-read the notice that I received from Cloudflare and didn't see that (although I might have missed it - if it was cryptically worded).

2. "might be affected by this attack"
Should only those specifically notified by CloudFlare do this, or are we recommending that EVEYRONE using Cloudflare do this?
They say it was only a couple hundred sites and they are personally notifying those site owners.

3. Does the 'secret key' need to be manually changed
Do we need to manually edit the configuration.php file, or can we change that within Joomla admin?

4. Who is JSST?

5. Password reset & User Activation Emails - list?
Is there any way within J! to see a list of pending password resets or activations?
(Actually, I know how to view the pending activations, just not password resets).
We will need to provide clear instructions on this so that admins can determine the impact of this action on users.

6. Changes to CloudFlare Cache
I'm guessing it would be wise to manually do a refresh of all CF cahce (do a complete refresh of all files)?

If you can answer these I'll get this written up shortly.

**Comment by zero-24** [comment]
>Who is JSST?

https://volunteers.joomla.org/teams/security-strike-team ;)

**Comment by zero-24** [comment]
> Password reset & User Activation Emails - list?
Is there any way within J! to see a list of pending password resets or activations?

It is on the same list / the user list in the backend if someone is required to change the PW there will be a label telling the admin that.

> Does the 'secret key' need to be manually changed
Do we need to manually edit the configuration.php file, or can we change that within Joomla admin?

Manually. Nothing like this can be done via the GUI.

**Comment by wilsonge** [comment]
1. "More concerning was that fact that chunks of in-flight HTTP requests for Cloudflare customers were present in the dumped memory. That meant that information that should have been private could be disclosed." Source: https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/
2. https://news.ycombinator.com/item?id=13719360 Read this. Whilst from their logs they identified 3k domains. Any search engine that crawls the site then exposes that info.
3. It needs to be manually changed. Best practices on how to change that is one of the many things I'm going to need to add to that post
4. What Tobias said
5. What Tobias said
6. I have no clue. I think Cloudflare have dealt with things their end. But I guess it can't hurt either?

**Comment by Sandra97** [comment]
The picture for the blogpost: 
![clouflare-blogpost](https://cloud.githubusercontent.com/assets/4682328/23342568/5f03b796-fc33-11e6-9189-cba3b93b950c.jpg)

**Comment by cpaschen** [comment]
There are a number of what appear to be gramatical issues with that post that I'd like to clean-up. Could you open access on that doc to either edit or comment level? (I'm only able to view with my cjo account).
I can help with getting this written up.
I'm thinking that we really should put the instructions for changing the secret key should just be a new jdoc. I've got some time available in the next couple hours that I could help get this out the door - but I will not be available for writing again until sometime Tuesday :-(

**Comment by wilsonge** [comment]
Sure. You should have an email. Remember this is only the Joomla part I'm writing. It needs a good summary. Like the wordfence article I linked to. We want our own version of that with our own Joomla specific information where they have the wordpress specific information

**Comment by wilsonge** [comment]
OK I've finished writing what I think needs to be in the article. Feel free to take it apart.

**Comment by cpaschen** [comment]
OK ... I'm just doing some 'cleaning up' and 'dumbing down' (so that even I can follow. [I've got a site with cloudflare that I'm dealing with so I can specifically test/confirm steps.

Just courious. Shouldn't we have all users to a full, manual cache cleaning (both on Joomla and Cloudflare after they invalidate sessions? (I've had some strange happenings back in the 3.4 days when I went through this process. Clearing both server and CF cache seemed to resolve/prevent problems.)

Also, do we have the JDocs article for resetting the secret key?
(Or do I have to do EVERYTHING myself??? :-)

**Comment by yvesh** [comment]
@cpaschen open your configuration.php in you joomla root, search for $secret and change the string in the single quotes (make sure it stays in single quotes) there:

`public $secret = 'SOMETHINNEW';`

That's it..

**Comment by cpaschen** [comment]
OK ... I think I am finally done.

**Comment by cpaschen** [comment]
I'm just going to put the 'instructions' for the fix in the content (per Yves). (Sorry Sandra, I just can't bring myself to write a new jdoc :-)

**Comment by Sandra97** [comment]
One day, I'll succeed to make you write something on JDocs ;)

**Comment by cpaschen** [comment]
OK ... I've completed my hacking at this.

Please take a review of this and let me know if you see any problems. I think I've included all the points that George mentioned we should have and also included a 'dummy's version' of the config instructions.

Please take a look at those to make sure I didn't post something improperly in that Step 2 point 3.

I do wish that there were a way for us to somehow make that $secret updateable via the admin GUI. I'm sure that there are going to be more 'novice' users who have sites using Cloudflare that aren't even going to know what an FTP program is :-(

Let me know if you see any problems.

Otherwise we need to get this posted Monday morning if possible.

(And we should also follow-up the post with a Social Media post referencing the article.

**Comment by mbabker** [comment]
> I do wish that there were a way for us to somehow make that $secret updateable via the admin GUI

Adding it to the UI is easy.  However it's not a value that really should ever change once a site is set up, hence the reason it's not anywhere to be found.

**Comment by cpaschen** [comment]
I've added social media text to the bottom of the document.

BTW ... I love the graphic!

**Comment by cpaschen** [comment]
RE: $secret - UI config

Unless you have a security issue with a CDN (I had one previously myself). 
But I completely agree that the very low number of times that it 'might' be useful doesn't warrant adding to the core (because I'm sure someone would either find a way to exploit that or users would just find a way to break things with it) :-)

When I say 'wish' it's kinda like I 'wish' that we had more JDocs - because I know full well that I could easily do either of those myself :-)

**Comment by cpaschen** [comment]
Sandra - can we add one more hasgtag to the graphic - #cloudflare ?

**Comment by Sandra97** [comment]
Here it is
![clouflare-blogpost](https://cloud.githubusercontent.com/assets/4682328/23356032/c699b04c-fcae-11e6-9cc5-3d543de6efdf.jpg)

**Comment by yvesh** [comment]
#jsst ;)

**Comment by wilsonge** [comment]
We don't need a JSST hashtag on this. It's not a core bug in any way

**Comment by yvesh** [comment]
okay, it's about joomla security and everyone sould know jsst ;)

**Comment by Sandra97** [comment]
I added the hashtags to the Tweet:
#Cloudflare Data Leak and #Joomla - What you need to know and do
LINK
#Security #data #Website #Cloud #JSST

**Comment by Sandra97** [comment]
Published: https://community.joomla.org/blogs/community/3101-cloudflare-data-leak-and-joomla.html
Closing this issue.

**Comment by yvesh** [comment]
Good work! Thank you

**Comment by wilsonge** [comment]
You star!

**Comment by MATsxm** [comment]
great feedbacks about the article even.... you won't believe it.... from the Froggies Community 😝

**Comment by cpaschen** [comment]
BTW ... thanks for everyone's contribution. I hope we can do more like this. It makes it VERY easy to get something out quickly when someone with 'technical' knowledge about an issue writes 'something' (even if only sketchy and even if not native english) and then we can 'compose' and then have tech re-review for technical accuracy.

Now my only question is ... who is the "Froggies Community"???

**Comment by MATsxm** [comment]
the one always on strike complaining about everything and that I'm supposed* to be part of...
(*I try to fight against this assumption for years now)

**Comment by wilsonge** [comment]
Froggies = French 

Glad to see as someone based in England I'm classified as a non-native 😂😂 (don't worry just pulling your leg I know that's not what you meant)
