### ISSUE TITLE
[copywriting] Joomla Features Campaign

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#71]
The Objective of this campaign is to do a series of Articles about key Joomla features as well as nice things in Joomla that people might not be aware of. 

The MIH session will be about getting a list of such features & ideas.. And hopefully get a few written. 

Here is the document where you can find the details https://docs.google.com/document/d/10iniPUcaiJ1tnmXFVcVHAktGaCtaIxQ1597psuq2ezU/edit#

**Comment by shirdesign** [comment]
Added some ideas in the comment part of the DOC. 
Can help writing the docs for the features I've suggested during the next few weeks.

**Comment by aDaneInSpain** [comment]
Please try to not only describe the features, but what are the **benefits** of the features. Also please remember that we are targeting **integrators** or **site creators** so the benefits should be aimed at them. So a benefit might be that it speeds up the __development__ of a site, or that it is easy to customize the behaviour etc.

An example could be ACL. It is a benefit to the developer because he can use it restrict and manage access for site administrators (his client) essentially preventing them from messing with stuff they should not. It is also great for him as it saves him having to develop this feature himself and it can be re-used in custom components. Write is from the perspective of the site developer, not the end client.

**Comment by mikeveeckmans** [comment]
benefits will be on a seperate copywriting, they can however be combined on the pages...

**Comment by mikeveeckmans** [comment]
#113

**Comment by Sandra97** [comment]
As we have decided to focus on benefits more than on features, I'm closing this issue.
You can see the doc about benefits in  issue #113
