### ISSUE TITLE
[STRATEGY] Define The Joomla campaign for Hosts

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#88]
https://docs.google.com/document/d/155-4aHyfFEFX2ZV2XUYUwZZZEjGO4geXa1YShRW2COM/edit

**Comment by Sandra97** [comment]
I would love to have a working group for relationships with hosting companies, so that they can promote better Joomla (by providing them up to date content, press releases...) But this requires human resources we don't currently have. So unfortunately I'm closing this issue and hope I can re-open it one day.
